### ISSUE TITLE
Callback getting called multiple times with the same attempt number

### ISSUE THREAD

**Issue by rightaway** [IndigoUnited/node-promise-retry#14]
I get numerous console.log output with the same attempt number before the attempt number gets incremented.

```
doing 2
doing 2
doing 2
...
doing 3
doing 3
doing 3
```

Why would the callback get executed again with the same attempt number?

```js
function retryCommand(command) {
  const options = { retries: 3 }
  return promiseRetry(options, (retry, number) => {
    if (number > 1) console.log(`doing ${number}`)
    return exec(command)
      .catch((err) => {
        if (errorIsRetriable(err)) {
          retry(err)
          // should there be a 'return' here? I tried it with and without, but same result
        }
        throw err
      })
  })
}
```

And then I use it by calling it from inside an `async` function like `await retryCommand('some-executable')`.

If it's important, here's what `exec` is (it's Node's built-in `child_process.exec` promisifed using the `pify` library).

```js
import childProcess from 'child_process'
import pify from 'pify'

const exec = pify(childProcess, { multiArgs: true }).exec
```

**Comment by carsy** [comment]
We have a test for that: https://github.com/IndigoUnited/node-promise-retry/blob/master/test/test.js#L31

Can you debug into `promise-retry` and log `number` right [here](https://github.com/IndigoUnited/node-promise-retry/blob/master/index.js#L29) on line 29?

**Comment by rightaway** [comment]
I put a `if (number > 1) console.log(`doing ${number} - from promise-retry`)` right before line 29, and in addition to my logging statement from the previous post, the output is like

```
doing 2 - from promise-retry
doing 2
doing 2 - from promise-retry
doing 2
doing 2 - from promise-retry
doing 2
...
doing 3 - from promise-retry
doing 3
doing 3 - from promise-retry
doing 3
doing 3 - from promise-retry
doing 3
```

**Comment by carsy** [comment]
@rightaway I tried to reproduce the error with the following sample:

```js
const childProcess = require('child_process')
const promiseRetry = require('promise-retry')
const pify = require('pify')

const exec = pify(childProcess, { multiArgs: true }).exec

function retryCommand(command) {
    const options = { retries: 3 }

    return promiseRetry(options, (retry, number) => {
        if (number > 1) console.log(`doing ${number}`)
        return exec(command)
        .catch(retry)
    })
}

retryCommand('ls -4')
.then(stdout => {
    console.log(`${stdout[0]}`)
})

```

and the output was:
```
doing 2
doing 3
doing 4
(node:87108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: ls -4
ls: illegal option -- 4
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

Can you provide a full sample that reproduces the error? That would be awesome! 😄 
Thanks

**Comment by carsy** [comment]
@rightaway any updates on this?

**Comment by rightaway** [comment]
@carsy I haven't been able to duplicate this in a full standalone sample, even though I'm getting it in the application, so it has something to do with the specific way my application is using it. I'll reopen the issue when I've identified what it is.
