### ISSUE TITLE
Array of promises is not working 

### ISSUE THREAD

**Issue by marcoapferegrino** [IndigoUnited/node-promise-retry#18]
Hi, guys
I am implementing some promises these promises make a request call (get) and if some of them fail the have to retry(make the request again or call the function again). 
And I do Promise.all to handle the results, the problem is the retry function is not waiting as a promise and the Promise all is executing first. 

```
const promiseRetry = require('promise-retry');
 localProjects.forEach(function(folder, index) {
          promiseRetry(function (retry, number) {
            console.log('attempt number', number);
            return getFolderHours(folder, {start: start, end: end})
                .catch(function (err) {
                  if (err.code === 'MISSING_TIMELOG') {
                    retry(err);
                  }
                  throw err;
                });
          },{
            retries: 5,
            factor : 2,
            minTimeout: 2000,
            maxTimeout: 4000
          }).then(function (values) {
                console.log('values: '  + values);
                localProjectsResolved.push(values); //pushing values in the array and is working ok but after PRomise.all
              }, function (err) {
                console.log('Some error')
              });
        });
//localProjectResults is empty cos is not waiting for the solved promises
 Promise.all(localProjectsResolved).then((localProjectResults) => {
            // got the results, send the request
          console.log('Results')
          console.log(localProjectResults); //EMPTY array
         /*some stuff to cal hours*/
          
            res.status(200).send({totalHours: totalHours, projects:localProjects});
        }).catch((error) => {
            res.status(409).send({mess: error}); //This response is sent when a request conflicts with the current state of the server.
        });
```

This work well and is returning the code 
```
var getFolderHours =  function(folder, period){
    return new Promise(function(resolve, reject) {
        request.get('https://www.url.com',{
            'auth': {
                'bearer':process.env.TOKEN
            }
        }, function (err, response, body){
            console.log(response.statusCode);
            if (!err){
             //some stuff code
                if(body){
                resolve()
                  } else { 
                     reject('MISSING_TIMELOG');
               }
                resolve(hours);
            } else {
                reject(err);
            }
        });
    });
};
```

**Comment by satazor** [comment]
I think you need to study how promise works because it seems you don't you understand them very well.

You should create localProjects using .map instead of .forEach. This will give you an array of promises that you can pass to Promise.all.

**Comment by marcoapferegrino** [comment]
But i am not creating localprojects I am lopping them and that data is already created , I am pushing into   localProjectsResolved but Promise.all is executing first when I use retry

**Comment by marcoapferegrino** [comment]
Here is my solution. U got right that was a problem of array promises. 
After all, I just push into the array the complete function retry. 


 localProjectsResolved.push(promiseRetry({
            retries: 5,
            factor : 2,
            minTimeout: 2000,
            maxTimeout: 4000
          }, function (retry, number) {
            console.log('attempt number', number);
            return getFolderHours(folder, {start: start, end: end})
                .catch(function (err) {
                  if (err === 'MISSING_TIMELOG') {
                    retry(err);
                  }
                  throw err;
                });
          }).then(function (values) {
            console.log('values: '  + values);
            return values;
          }, function (err) {
            console.log(err)
            console.log('Some error')
          }))
