### ISSUE TITLE
Undefined error case

### ISSUE THREAD

**Issue by guybedford** [IndigoUnited/node-promise-retry#22]
Howdy @satazor, hope you are really well :)

I've run into a case where this is throwing an undefined error due to https://github.com/IndigoUnited/node-promise-retry/blob/master/index.js#L30 being `true` and `err.retried` being `undefined`. The scenario was that I'm doing a manual retry check around `lockfile.check` (https://github.com/IndigoUnited/node-proper-lockfile#checkfile-options-callback), which throws a EPROMISERETRY error without this `retried` property.

Perhaps the conditional just needs to include a check for this property existing.

**Comment by satazor** [comment]
Hello @guybedford!

Could you post a reproducible test code so that it will be easier to understand and debug?

**Comment by guybedford** [comment]
Thanks for the quick response! Hmm, it seems it may have been some faulty promise wiring causing the issue (possibly by not properly propagating the error thrown by `retry` as I was calling it inside a new Promise construct). All seems to be working now, of course no fault in your code :)

**Comment by satazor** [comment]
No problem :)

Hugs :)
