### ISSUE TITLE
Need a clear example on how to retry in case of a specific error.

### ISSUE THREAD

**Issue by shaheenmasood** [IndigoUnited/node-promise-retry#24]
Hi,

I would like to use the module to retry conditionally a promise function. I have a db function that returns a promise or error. If the error is duplicate key I want to retry. I looked an your example:

// Conditional example 
promiseRetry(function (retry, number) {
    console.log('attempt number', number);
 
    return doSomething()
    .catch(function (err) {
        if (err.code === 'ETIMEDOUT') {
            retry(err);
        }
 
        throw err;
    });
})
.then(function (value) {
    // .. 
}, function (err) {
    // .. 
});

I am guessing "retry" parameter is the function I want to try. What is "doSomething()"? Are we catching the error from "doSomething()"?  Why? I want to catch the error from "retry" function that returns a promise.

Also, my "retry" function takes a parameter. How do I pass it here?

Thanks in advance for a clear example. I am looking forward to it.

-- shaheen

**Comment by satazor** [comment]
`retry` is a function that should be called if your intent is to retry after capturing an error.
`doSomething` can be anything asyncronous, e.g.: fetch something from a DB.

Hope this makes sense.
