### ISSUE TITLE
pass arguments retry fn

### ISSUE THREAD

**Issue by ddemolina** [IndigoUnited/node-promise-retry#26]
Hi,
When I define the fn to retry in promiseRetry I can't see how to specify extra arguments( in adition to retry and number) in order to receive those arguments when I call retry. For example:
```
promiseRetry( (retry, retryAttemps, otherParameter) => {
if( otheParameter) 
return fetch(something)
.catch(error => retry(error, otherParameterValue))
else
return fetch(anotherThing)
.catch(error => retry(error, otherParameterValue))
}, {retries: 100})
```

Thanks!

**Comment by satazor** [comment]
You have to pass fn as a closure that carry those parameters.

**Comment by ddemolina** [comment]
Thank you!
