### ISSUE TITLE
Allow us to choose our promise implementation

### ISSUE THREAD

**Issue by SimonSchick** [IndigoUnited/node-promise-retry#5]
It would be super handy if we could determine the implementation of the promise returned by this function.

This is helpful when using promise libs such as bluebird and Q and you don't want to miss on their functionality.

Examples of how it could be done:

```javascript
const promiseRetry = require('promise-retry');
promiseRetry.setPromiseImplementation(Bluebird || q || whatever);
 // or
const promiseRetry = require('promise-retry')(Bluebird || q || whatever); // I prefer this one as it avoids conflicts by returning a new function.
```

I've done the same in my [library](https://github.com/SimonSchick/event-promisify#simple-promisification).

`promise-try` already supports choosing your own implementation so this should be easy to do.

**Comment by satazor** [comment]
Please my comments on: https://github.com/IndigoUnited/node-promise-retry/pull/3

**Comment by SimonSchick** [comment]
I am aware of this, feels more like a work around tho.

**Comment by satazor** [comment]
If you want to do this globally I suggest overwriting global.Promise with the implementation you want. This is what makes most sense and doesnt require me and other libraries to support this stuff

**Comment by wulfsolter** [comment]
+1 for proposal from @satazor
