### ISSUE TITLE
retries: 0 should retry indefinitely

### ISSUE THREAD

**Issue by gunar** [IndigoUnited/node-promise-retry#8]
The current implementation is that it doesn't retry when `options = { retries: 0 }`. As I understand, if you don't want to retry, simply skip this package.

On the other hand, allowing for indefinite retries would be super useful.

Thank you.

**Comment by gunar** [comment]
I've also tried `{ retries: Infinity }` but that throws a very gross error :)

![image](https://cloud.githubusercontent.com/assets/7684574/16280784/a9006a3e-3897-11e6-85dc-4a4f86ad6872.png)

**Comment by satazor** [comment]
This module uses retry underneath so I suggest you to request that feature in the module itself, see: https://github.com/tim-kos/node-retry/issues/5

**Comment by satazor** [comment]
Closing this in favor of tim-kos/node-retry#5, once it's done it will be available here.
